# Generated by Django 5.0.3 on 2024-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo_content", models.TextField()),
            ],
        ),
    ]
