# Generated by Django 5.0.3 on 2024-08-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0002_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_content", models.CharField(max_length=400)),
            ],
        ),
    ]
