# Generated by Django 5.0.3 on 2024-08-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0004_createurl_delete_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="text_content",
            field=models.TextField(default=""),
        ),
    ]
