# Generated by Django 5.0.3 on 2024-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0005_todo_text_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
