# Generated by Django 5.0.3 on 2024-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0006_alter_todo_text_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Done_todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="todo",
            name="text_content",
            field=models.TextField(default=""),
        ),
    ]
