# Generated by Django 5.0.3 on 2024-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0007_done_todo_alter_todo_text_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Star_todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
            ],
        ),
    ]
