# Generated by Django 5.0.3 on 2024-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0008_star_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
