# Generated by Django 5.0.3 on 2024-09-27 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0009_todo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="star_todo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="todo_image"
            ),
        ),
        migrations.AddField(
            model_name="star_todo",
            name="todo",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Table.todo"
            ),
        ),
        migrations.AlterField(
            model_name="star_todo",
            name="text_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="todo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="todo_image"
            ),
        ),
    ]
