# Generated by Django 5.0.3 on 2024-09-27 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0010_star_todo_image_star_todo_todo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="star_todo",
            name="todo",
        ),
    ]
