# Generated by Django 5.0.3 on 2024-09-27 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0012_remove_star_todo_image_star_todo_todo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="star_todo",
            name="Todo",
        ),
    ]
