# Generated by Django 5.0.3 on 2024-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0013_remove_star_todo_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="star",
            field=models.BooleanField(default=False),
        ),
    ]
