# Generated by Django 5.0.3 on 2024-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0014_todo_star"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="star",
            new_name="selected",
        ),
        migrations.AlterField(
            model_name="todo",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="todo_image"
            ),
        ),
    ]
