# Generated by Django 5.0.3 on 2024-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0015_rename_star_todo_selected_alter_todo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="selected",
        ),
        migrations.AddField(
            model_name="todo",
            name="star_selected",
            field=models.BooleanField(default=False),
        ),
    ]
