# Generated by Django 5.0.3 on 2024-09-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0016_remove_todo_selected_todo_star_selected"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="star_selected",
            new_name="selected",
        ),
        migrations.AddField(
            model_name="star_todo",
            name="todo",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Table.todo"
            ),
        ),
    ]
