# Generated by Django 5.0.3 on 2024-10-03 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0017_rename_star_selected_todo_selected_star_todo_todo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="selected",
            new_name="star",
        ),
        migrations.AlterField(
            model_name="star_todo",
            name="todo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Table.todo",
            ),
        ),
    ]
