# Generated by Django 5.0.3 on 2024-10-03 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0018_rename_selected_todo_star_alter_star_todo_todo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Star_todo",
        ),
    ]
