# Generated by Django 5.0.3 on 2024-10-10 03:08

import Table.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0019_delete_star_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Star_todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("text_content", models.TextField(default="")),
            ],
        ),
        migrations.RemoveField(
            model_name="todo",
            name="star",
        ),
        migrations.AlterField(
            model_name="todo",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=Table.models.custom_upload_to,
                verbose_name="todo_image",
            ),
        ),
    ]
