# Generated by Django 5.0.3 on 2024-10-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0020_star_todo_remove_todo_star_alter_todo_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreateUrl",
        ),
        migrations.DeleteModel(
            name="Done_todo",
        ),
        migrations.DeleteModel(
            name="Star_todo",
        ),
        migrations.AddField(
            model_name="todo",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="star",
            field=models.BooleanField(default=False),
        ),
    ]
