# Generated by Django 5.0.3 on 2024-10-10 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Table", "0021_delete_createurl_delete_done_todo_delete_star_todo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Text",
        ),
    ]
